#!/bin/bash
#set -x
cd $(dirname "$0")
export PATH=$PATH:$(pwd)

# main reporting tool - daily details for selected tasks

[ -z "GTIMELOG_TAGCHAR" ] && GTIMELOG_TAGCHAR='@'
export GTIMELOG_TAGCHAR

[ -z "$1" ] && { . gtlsreport_help; exit 10; }
[ -n "$4" ] && { echo "Max 3 params allowed"; exit 10; }

if [ "$#" -eq 1 ]; then
    PARAM1="$1"
    PARAM2="0"
    CATEGORY=""
else
    eval LASTPARAM=$`echo $#`
    if [[ "$LASTPARAM" =~ ^[\#@A-Z] ]]; then 
        [ "$#" -eq 2 ] && { PARAM1="$1"; PARAM2="0"; CATEGORY="$2"; }
        [ "$#" -eq 3 ] && { PARAM1="$1"; PARAM2="$2"; CATEGORY="$3"; }
    else
        [ "$#" -eq 2 ] && { PARAM1="$1"; PARAM2="$2"; CATEGORY=""; }
        [ "$#" -eq 3 ] && { PARAM1="$1"; PARAM2="$2"; CATEGORY=""; }
    fi
fi

if [ -n "$CATEGORY" ]; then
    if [[ "$CATEGORY" =~ ^[\#@] ]]; then
        # we have a tag
        gtllist | grep -E '^[0-9 :-]{15,} .*[ ,.?]'${CATEGORY}'([ ,]|$)' | gtlsel "$PARAM1" "$PARAM2" | gtlsum
    else
        [ -n "${CATEGORY}" ] && { export GTIMELOG_CATEGORY="${CATEGORY}"; }
        export GTIMELOG_CATEGORY="${CATEGORY}"
        # we have a category
        gtllist | grep -E "^[0-9 :-]{15,} ${CATEGORY}[^ :]*: " | gtlsel "$PARAM1" "$PARAM2" | gtlsum
    fi
fi
[ -z "$CATEGORY" ] && gtllist | gtlsel "$PARAM1" "$PARAM2" | gtlsum

