#!/bin/bash

# main reporting tool - tasks group sums for selected tasks and it's all subcategories - character '_' seperates subcategories

[ -z "$1" ] && { . gtlsreport_help; exit 10; }
[ -n "$4" ] && { echo "Max 3 params allowed"; exit 10; }

if [ "$#" -eq 1 ]; then
    PARAM1="$1"
    PARAM2="0"
    CATEGORY=""
else
    eval LASTPARAM=$`echo $#`
    if [[ "$LASTPARAM" =~ ^[A-Z] ]]; then 
        [ "$#" -eq 2 ] && { PARAM1="$1"; PARAM2="0"; CATEGORY="$2"; }
        [ "$#" -eq 3 ] && { PARAM1="$1"; PARAM2="$2"; CATEGORY="$3"; }
    else
        [ "$#" -eq 2 ] && { PARAM1="$1"; PARAM2="$2"; CATEGORY=""; }
        [ "$#" -eq 3 ] && { PARAM1="$1"; PARAM2="$2"; CATEGORY=""; }
    fi
fi

[ -n "$CATEGORY" ] && gtllist | grep -E "^[0-9 :-]{15,} ${CATEGORY}[^ :]*: " | gtlsel "$PARAM1" "$PARAM2" | gtlsumcats
[ -z "$CATEGORY" ] && gtllist | gtlsel "$PARAM1" "$PARAM2" | gtlsumcats


